"""add plan anual, plan anual items, materials

Revision ID: 3f041ca8d7b7
Revises: c1d2e3f4a5b6
Create Date: 2026-05-09 18:16:43.543426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f041ca8d7b7'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_anuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_anual_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_anual_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=32), nullable=False),
    sa.Column('oa', sa.String(length=16), nullable=False),
    sa.Column('cantidad_clases', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_anual_id'], ['plan_anuales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_anual_items_material_id'), 'plan_anual_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_plan_anual_items_oa'), 'plan_anual_items', ['oa'], unique=False)
    op.create_index(op.f('ix_plan_anual_items_plan_anual_id'), 'plan_anual_items', ['plan_anual_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_anual_items_plan_anual_id'), table_name='plan_anual_items')
    op.drop_index(op.f('ix_plan_anual_items_oa'), table_name='plan_anual_items')
    op.drop_index(op.f('ix_plan_anual_items_material_id'), table_name='plan_anual_items')
    op.drop_table('plan_anual_items')
    op.drop_table('plan_anuales')
    op.drop_table('materials')
    # ### end Alembic commands ###
